[package]
name = "rsynth"
version = "0.1.0"
authors = ["Jason Reed <jcreed@gmail.com>"]
edition = "2021"

[[bin]]
name = "alsa-test"
path = "src/alsa-test.rs"

[dependencies]
alsa = "0.9.0"
anyhow = "1.0"
midir = "0.9.1"
