[package]
name = "rsynth"
version = "0.1.0"
authors = ["Jason Reed <jcreed@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.3"
portaudio = "^0.7.0"
coremidi = "0.3.0"
midir = "0.5.0"
# portmidi = "^0.2"
